tap "homebrew/bundle"
tap "homebrew/core"
tap "nhemsley/env", "https://github.com/nhemsley/homebrew-env.git"
tap "thoughtbot/formulae"

brew "nhemsley/env/homebrew-env"
#brew "go"
#brew "nvm"
#brew "ruby-build"
#brew "rbenv"
#brew "rbenv-gemset"
brew "rcm"
